title: Raspberry Pi Pico webserver
hero_image: images/banner.png
description: Serve a simple web page from a Raspberry Pi Pico 2 W
version: 1
listed: false
landing: true
copyedit: false
last_tested: "2026-04-24"
steps:
  - title: Serve a webpage from your Pico 2 W
  - title: Just a test